feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        enable: true  #打开熔断
        requestVolumeThreshold: 2  #请求错误数
        sleepWindowInMilliseconds: 5000   #熔断时长，默认为5000，即5s钟
        errorThresholdPercentage: 50	#错误率，默认50%
        forceOpen: false	#强制打开断路器，默认false
        forceClose: false	#强制关闭断路器，默认false
management:
  endpoints:
    web:
      exposure:
        include: "*" #默认开启health,info
  endpoint:
    health:
      show-details: ALWAYS